### ISSUE TITLE
Certificates still created when template "None" selected

### ISSUE THREAD

**Issue by rachelsquirrel** [woocommerce/sensei-certificates#107]
When no certificate template is selected for a course a certificate is still generated upon completion of the course. Is it possible to turn off certificates for specific courses? The certificate is not emailed to the learner but it appears in the Dashboard at Certificates > Certificates.

This was reported in 443985-zd-woothemes.

**Comment by pgk** [comment]
@rachelsquirrel I can't reproduce. Can we get steps to reproduce?

**Comment by rachelsquirrel** [comment]
I can't reproduce this now either. I'll follow-up with the user to see whether it's still happening for them.

**Comment by donnapep** [comment]
I was able to reproduce this by:
1. Changing the _Certificate Template_ of a course from a template to _None_.
2. As an admin user, starting the course and stepping through each lesson until complete.
3. Once the last lesson was completed, an empty certificate was generated.
