### ISSUE TITLE
Issue with RTL and custom font

### ISSUE THREAD

**Issue by rachelsquirrel** [woocommerce/sensei-certificates#109]
A user reports that when they upload a custom font by following the instructions [here](https://docs.woocommerce.com/document/sensei-certificates-multilingual-fonts-support/) it changes the meaning of the words. 

Here's the text they're trying to display:

![expected](https://cloud.githubusercontent.com/assets/7946521/17297514/eb9a4b28-57fd-11e6-83ec-3b36d573dbaf.jpg)

But in the certificate it displays like this:

![explain](https://cloud.githubusercontent.com/assets/7946521/17297520/f13ac9a4-57fd-11e6-8df9-0631996397b2.jpg)

As a test they also tried using Arial and had the same problem. They say that if the course name is "Great" the text is showing as "taerG" which suggests it's an issue with RTL. 

446069-zd-woothemes

**Comment by donnapep** [comment]
Closing as there are not enough details to reproduce this.
