### ISSUE TITLE
All user roles can access Certificates menu items.

### ISSUE THREAD

**Issue by jenhooks** [woocommerce/sensei-certificates#112]
Only Administrators and Teacher roles are meant to be able to access Certificates menu items in wp-admin, however, Editors, Contributors, and Authors are actually able to [add new certificates](https://github.com/woothemes/sensei-certificates/issues/90) as well (though they [can't actually view them](http://d.pr/i/150Ov) after creation). Those user roles are also able to view the Certificates and Certificates Templates screens.

To reproduce:
1. Create an editor, contributor, or author test account on a site with Sensei Certificates installed.
2. Navigate to wp-admin.
3. Click on any of the Certificates submenu items. 
4. You will be able to make a new certificate, view the main Certificates screen, and Certificates Templates screen.
5. You will encounter a "You are not allowed to view this Certificate." notification if you attempt to view any actual certificates.

Ticket context: 462799-zd-woothemes

**Comment by fredperes** [comment]
I confirm the issue. Tried using "wp role editor" plugin with no luck.
