### ISSUE TITLE
Access to certificates for Teachers

### ISSUE THREAD

**Issue by lschuyler** [woocommerce/sensei-certificates#119]
In 549627-zd-woothemes we received an enhancement request to allow teachers to have access to certificates when they are not set to public:

> This site is for an Interior Design School. They used to be an 
> 'offline' school but have transferred it all online now. When their 
> students would complete a course they would issue them with a 
> certificate and keep a copy for themselves. They would like to be able 
> to continue to do that so as to have an archive of them all. I am 
> reluctant to give thee tutors admin access as the back end would look 
> too complicated for them then as well as there being the chance of them 
> accidentally doing anything undesired! So I'd like to be able to keep 
> them as tutors and be able to see the certificates that they have 
> effectively issued themselves. -I suppose that brings me to another 
> reason for needing access: If there were a query by one of the students 
> about their certificate, the Tutor would not have access to the 
> certificate to know what the student was referring to. At present the 
> Tutor can go as far as seeing the 'View Certificate' link next to the 
> student's name, but when they click it they get access denied.

Maybe this enhancement to lend itself to a user role/permissions setting?

**Comment by pgk** [comment]
Similar to #125 which allows access to certificates by Teachers and Admins. Closing for now, if it's not the same feel free to reopen
