### ISSUE TITLE
PHP 7 Error

### ISSUE THREAD

**Issue by BusinessBloomer** [woocommerce/sensei-certificates#120]
I get this when testing my site on PHP 7 (which fails, as Sensei Certificates 1.0.13 is apparently not compatible?):

FILE: /---/public_html/wp-content/plugins/sensei-certificates/lib/tfpdf/font/unifont/ttfonts.php
----------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------
 72 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
----------------------------------------------------------------------------------------------------------

FILE: /---/public_html/wp-content/plugins/sensei-certificates/lib/tfpdf/tfpdf.php
------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AND 1 WARNING AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------
   79 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
 1264 | ERROR   | Function set_magic_quotes_runtime() is deprecated since PHP 5.3 and removed since PHP 7.0
------------------------------------------------------------------------------------------------------------

**Comment by PDowney** [comment]
Lol, so this plugin isn't compatible with PHP 7 after all this time? Such a mess, and it really makes Sensei look very bad.

**Comment by annezazu** [comment]
@pgk  can you take a look at this?

**Comment by pgk** [comment]
@BusinessBloomer thanks, Is this output from `phpcs`? 

That line will never run on php > 5.4 

```
// Ensure runtime magic quotes are disabled
if(get_magic_quotes_runtime())
    @set_magic_quotes_runtime(0);
```

Because `get_magic_quotes_runtime()` will always return false (see [here](http://php.net/manual/en/function.get-magic-quotes-runtime.php))

Warnings addressed in https://github.com/woocommerce/sensei-certificates/commit/80e01664b36153f3bc5e3e11e39cd4625bae016f

**Comment by BusinessBloomer** [comment]
@pgk 

In relation to > "is this output from phpcs?", well, I have no idea.

I ran a tool from Siteground which lets you test if your website is compatible with PHP7 before upgrading to it, and those are the errors I got :)
