### ISSUE TITLE
Fatal error on install

### ISSUE THREAD

**Issue by danjjohnson** [woocommerce/sensei-certificates#130]
User reports fatal error when installing for the first time:

> Fatal error: Class 'Woothemes_Sensei_Certificates_Utils' not found in .../wp-content/plugins/sensei-certificates/classes/class-woothemes-sensei-certificates-data-store.php on line 18

https://github.com/woocommerce/sensei-certificates/blob/f6e4168d7313e55e9e2dfb7786d71307b7c45c9d/classes/class-woothemes-sensei-certificates-data-store.php#L18

Presumably similar to this:
https://github.com/woocommerce/sensei-certificates/commit/f6e4168d7313e55e9e2dfb7786d71307b7c45c9d

585361-zd-woothemes
648604-zd-woothemes

Ping @pgk

**Comment by annezazu** [comment]
@pgk repinging just in case :)

**Comment by gaurav1984** [comment]
I can confirm that [302f80c](https://github.com/woocommerce/sensei-certificates/commit/302f80c4c93c93015bb094fd62adf88ecb8df219) fixes the bug.

Steps to reproduce the bug, on a new install of WordPress
1. Install Sensei
2. Import sample data
3. Install sensei-certificates plugin
4. On activation causes Fatal error

**Comment by gaurav1984** [comment]
In 618454-zen the user is reporting that the issue is still happening.

They have Sensei v 1.9.16 & Sensei Certificates v 1.0.16 installed on their site.

**Comment by rachelsquirrel** [comment]
Also reported in 612183-zen.

**Comment by gaurav1984** [comment]
636366-zen

**Comment by gaurav1984** [comment]
638651-zen

**Comment by dsmithweb** [comment]
also 649713-zen

**Comment by deskroid** [comment]
Hey guys! Any updates on this? This issue seems to be very much there - just because very few customers use it, there are not many tickets about it :)

**Comment by pgk** [comment]
@deskroid The issue is fixed in #131 can you verify it fixes it for you?

**Comment by deskroid** [comment]
Thanks! I have forwarded this to the customer. Will update here once they get back.

**Comment by davidcavalcante** [comment]
Still waiting...

**Comment by deskroid** [comment]
The customer hasn't replied yet and the ticket is auto-closed at this time. Let's close this issue as Solved - if the customer comes back, we will re-open. I have tested this myself and it works so I guess we should be fine 👍

**Comment by davidcavalcante** [comment]
It does not work for me. It is giving the same error, and I have the updated versions of Sensei and Wordpress. This error is causing me SERIOUS problems. I really need the solution.
Thanks!

**Comment by davidcavalcante** [comment]
Can you give me the solution to the problem?

**Comment by PDowney** [comment]
It's probably time to start looking at another LMS. WooCommerce isn't focusing on Sensei much at all and it's lagged behind feature wise. Certificates is a huge feature that is totally ignored and currently broken for many.  

I'm already in the process of moving my large site off of Sensei.

**Comment by davidcavalcante** [comment]
That sucks! Because we buy Sensei... Do you recommend something else that works with Woocommerce (Wordpress)?

**Comment by rachelsquirrel** [comment]
@davidcavalcante Did you try the fix here https://github.com/woocommerce/sensei-certificates/pull/131 ? 

If you tried that and it didn't work can you please open a ticket with us so we can take a closer look at your site? You can submit a ticket through our website at https://woocommerce.com/contact-us/.

**Comment by davidcavalcante** [comment]
Work, thanks!

**Comment by aheckler** [comment]
734450-zen

**Comment by aheckler** [comment]
741362-zen
