### ISSUE TITLE
Error when previewing a certificate

### ISSUE THREAD

**Issue by mnoleto** [woocommerce/sensei-certificates#133]
I'm getting the following error when previewing a user generated certificate:
`FPDF error: Some data has already been output, can't send PDF file`

The preview for the certificate template works fine.

**Comment by mnoleto** [comment]
I will appreciate with any can help me with this issue.
I tried with PHP 7 and 5.6, also changed the allowed memory:
`define('WP_MEMORY_LIMIT', '256M');
define( 'WP_MAX_MEMORY_LIMIT', '256M' );`

**Comment by donnapep** [comment]
Hi there! I'd recommend opening a [Support ticket](https://woocommerce.com/my-account/create-a-ticket/?primary=broken&select=152116&form=ticket) if you are still experiencing this problem. They'll be able to help determine if this is a bug in the plugin, or if it's an issue specific to your site. Thx!
