### ISSUE TITLE
Unique code for certificate validation

### ISSUE THREAD

**Issue by digomiero** [woocommerce/sensei-certificates#135]
Hey guys.
It would be nice to be possible to validate the certificate in our website. So in each certificate there would be a line saying "To verify the authenticity of this certificate, please visit www.domain.com/verify and insert this code: XXXYYY123"
This would be an unique code that, when inserted, would return basic info such as Course name, Student name, and Date of Conclusion.

BR,

Diego

**Comment by donnapep** [comment]
This is not a priority at this time. Thx.
