### ISSUE TITLE
Open Certificate in Admin Painel

### ISSUE THREAD

**Issue by keviinlouis** [woocommerce/sensei-certificates#136]
When i try to see a certificate, he dosen't open the pdf, instead he show this 
![image](https://user-images.githubusercontent.com/1619231/32245500-1227fda4-be63-11e7-8c7f-0f3c77532110.png)

if i change the href of link and put preview=true, works
certificate/cb561881/ -> Dosen't work
certificate/cb561881/?preview=true -> work

how to fix that and if it's not a bug, how can i change the link in the admin painel?

tnks

**Comment by donnapep** [comment]
Hi there! I'd recommend opening a [Support ticket](https://woocommerce.com/my-account/create-a-ticket/?primary=broken&select=152116&form=ticket). They'll be able to help determine if this is a valid bug, or if this is an issue that is perhaps specific to your site. Thx!
