### ISSUE TITLE
FOpen error

### ISSUE THREAD

**Issue by Adminifhta** [woocommerce/sensei-certificates#146]
Cannot view certificate due to error: FPDF error: Can't open image file: https://[filepath].png

This was working correct until i reinstalled the site after a crash with plugin "All-in-One WP Migration".
Service provider informed me that FOpen should not have been on and they have no intention of opening it again as it is a security risk.
Any suggestions on how to work around this problem?

**Comment by richardmtl** [comment]
Hi! Closing this as you have already contacted us via email in ticket 1163372-zen.
