### ISSUE TITLE
Add image size advisory comment to the template editor

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/sensei-certificates#156]
Reported on 1373463-zen

While image guidelines for certificates can be found in our documentation here: https://docs.woocommerce.com/document/sensei-certificates/#image-guidelines , users seem to find their site layout has changed after using images that does not follow the previous guidelines and image resolution changes, but are unsure why this happened.

We could add just a little disclaimer to clarify this to the certificate settings:

User comments:
> I am suggesting that this under the certificate in the Edit Certificate Template editor, under the link "Set certificate image" a block of text that clearly states "Changing image resolution will change size and position of text blocks."

<img width="1267" alt="screen shot 2018-08-28 at 14 45 40" src="https://user-images.githubusercontent.com/3812076/45012812-f7693f00-b042-11e8-83a8-e299fae670f8.png">

**Comment by donnapep** [comment]
I don't think a disclaimer like this is necessary, as the in-editor preview shows how the text will be positioned on the image.
