### ISSUE TITLE
Improve Admin Screen Options

### ISSUE THREAD

**Issue by Adminifhta** [woocommerce/sensei-certificates#162]
I did not firnd a Sensei thread so i am submitting it here. Please move to where correct.

Can we have a Sensei Admin Screen Options feature similar to Woocommerce Screen Options that include the Pagination to set Number of items per page option and have it persistent across all admin screens.

![image](https://user-images.githubusercontent.com/30009544/48717325-11adc480-ec11-11e8-9120-910bd4b3f6cd.png)

**Comment by donnapep** [comment]
@Adminifhta Could you clarify which page you would like to have this screen option added to? The Pagination option already exists for all relevant admin screens in Sensei LMS and Sensei Certificates (e.g. Courses, Lessons etc.).

**Comment by Adminifhta** [comment]
Hi Donna, the Manage Learners per course page (view=learners) page please and also please make the table sortable by header for Learners, Date Started and Status.

**Comment by donnapep** [comment]
Thanks! I'm going to close this issue since it belongs in the [Sensei LMS repo](https://github.com/Automattic/sensei/issues/2781).
