### ISSUE TITLE
Add Hungarian translation

### ISSUE THREAD

**Issue by amroland** [woocommerce/sensei-certificates#168]
I have translated Sensei Certificates to Hungarian.
Do you need it?

Anyway, I have translated all additional Sensei plugins to Hungarian (Sensei Course Progress, Sensei Media Attachments, Sensei Share Your Grade, Sensei Course Participants and Sensei Content Drip). If you need, I can forward them too.

[sensei-certificates-hu_HU.zip](https://github.com/woocommerce/sensei-certificates/files/2632683/sensei-certificates-hu_HU.zip)

**Comment by donnapep** [comment]
Addressed in #170.

**Comment by donnapep** [comment]
@amroland Would appreciate a quick test to ensure Hungarian translations work for you in the 2.0 Beta. More details can be found [here](https://senseilms.com/2019/03/19/sensei-certificates-and-sensei-course-progress-2-0-betas/). Thx!

**Comment by amroland** [comment]
@donnapep Is it good if I test it with Sensei 1.12.1? Or should I test it with Sensei 2.0?

**Comment by amroland** [comment]
@donnapep 
I refreshed it from the new POT file (2.0). There were some untranslated row. You can find attached the new files below:
[sensei-certificates-hu_hu.zip](https://github.com/woocommerce/sensei-certificates/files/2991744/sensei-certificates-hu_hu.zip)

I checked Sensei Certificates 2.0 with Sensei 1.12.1. Everything works fine!

**Comment by amroland** [comment]
@donnapep 
I tested it. I have only found 1 error.
On the picture below you can see that if a Certificate Template is being edited the translated words are 1 character shorter. The last characters don't appear.
![Képernyőfotó 2019-03-23 - 11 42 06](https://user-images.githubusercontent.com/39312392/54865180-e0313b00-4d61-11e9-881e-37d202c32326.png)

As I mentioned the above comment I refreshed PO file with the latest POT file. You can find it attached above.
