### ISSUE TITLE
Cannot create certificate with special characters

### ISSUE THREAD

**Issue by ajinabraham** [woocommerce/sensei-certificates#169]
Creating a certificate with characters like `š` break the entire text content.
I have a user with name containing the grapheme Š, š (S with caron) and it breaks the text in certificate generation. It messes the entire text in the section where this character is present.

<img width="183" alt="screenshot 2019-01-25 at 12 00 52 am" src="https://user-images.githubusercontent.com/4301109/51700089-4d5f7300-2034-11e9-9cbc-b42b5355cd3f.png">

**Comment by beags121** [comment]
Ditto this - a user with an Ö (umlaut) in their name caused the certificate link to error:

`sensei certificates Fatal error: Uncaught Error: Call to undefined function mb_convert_encoding() in /var/www/site/wp-content/plugins/sensei-certificates/lib/tfpdf/tfpdf.php:2268 Stack trace: #0 /var/www/site/wp-content/plugins/sensei-certificates/lib/tfpdf/tfpdf.php(784): tFPDF->UTF8ToUTF16BE('Nina K\xC3\xB6hnke ', false) #1 /var/www/site/wp-content/plugins/sensei-certificates/lib/tfpdf/tfpdf.php(952): tFPDF->Cell('2090', '85', 'Nina K\xC3\xB6hnke ', 0, 2, 'C', false) #2 /var/www/site/wp-content/plugins/sensei-certificates/classes/class-woothemes-sensei-pdf-certificate.php(264): tFPDF->MultiCell('2090', '85', 'Nina K\xC3\xB6hnke ', 0, 'C') #3 /var/www/site/wp-content/plugins/sensei-certificates/classes/class-woothemes-sensei-certificates.php(660): WooThemes_Sensei_PDF_Certificate->textarea_field(Object(tFPDF), 'Nina K\xC3\xB6hnke ', 0, Array, Array) #4 /var/www/site/wp-includ in /var/www/site/wp-content/plugins/sensei-certificates/lib/tfpdf/tfpdf.php on line 2268`

**Comment by danjjohnson** [comment]
Also reported in 2237406-zen

**Comment by donnapep** [comment]
@ajinabraham @beags121 Although I'm not able to reproduce this, I believe it may be because the `mbstring` PHP extension is not installed on the server. You can install it by running the following command:

`sudo apt-get install php-mbstring`

If you don't have this level of access to your server, you may need to ask for assistance from your hosting provider.

Please let me know how it goes.

**Comment by beags121** [comment]
I've had my host activate that PHP extension but the error still remains I'm afraid

`Fatal error: Uncaught Error: Call to undefined function mb_convert_encoding() in /var/www/britishbutlerinstitute.com-multi/wp-content/plugins/sensei-certificates/lib/tfpdf/tfpdf.php:2268 Stack trace: #0 /var/www/britishbutlerinstitute.com-multi/wp-content/plugins/sensei-certificates/lib/tfpdf/tfpdf.php(784): tFPDF->UTF8ToUTF16BE('Nina K\xC3\xB6hnke ', false) #1 /var/www/britishbutlerinstitute.com-multi/wp-content/plugins/sensei-certificates/lib/tfpdf/tfpdf.php(952): tFPDF->Cell('2090', '85', 'Nina K\xC3\xB6hnke ', 0, 2, 'C', false) #2 /var/www/britishbutlerinstitute.com-multi/wp-content/plugins/sensei-certificates/classes/class-woothemes-sensei-pdf-certificate.php(264): tFPDF->MultiCell('2090', '85', 'Nina K\xC3\xB6hnke ', 0, 'C') #3 /var/www/britishbutlerinstitute.com-multi/wp-content/plugins/sensei-certificates/classes/class-woothemes-sensei-certificates.php(819): WooThemes_Sensei_PDF_Certificate->textarea_field(Object(tFPDF), 'Nina K\xC3\xB6hnke ', 0, Array, Array) #4 /var/www/britishbutlerinstitute.com-multi/wp-includ in /var/www/britishbutlerinstitute.com-multi/wp-content/plugins/sensei-certificates/lib/tfpdf/tfpdf.php on line 2268

The site is experiencing technical difficulties.`

**Comment by ajinabraham** [comment]
Sorry for being late. That was it
Fixed with `apt install php7.2-mbstring
