### ISSUE TITLE
Missing text on certificate background image for non-English site language

### ISSUE THREAD

**Issue by amroland** [woocommerce/sensei-certificates#178]
On any other language than English, every last characters of the position texts disappear on the Certificate Background panel.

English:
![Képernyőfotó 2019-04-12 - 10 34 59](https://user-images.githubusercontent.com/39312392/56024369-2bf75480-5d10-11e9-8501-4ebab1697b00.png)

Hungarian:
![Képernyőfotó 2019-04-12 - 10 36 39](https://user-images.githubusercontent.com/39312392/56024387-34e82600-5d10-11e9-9f97-c367f9fce8c4.png)

Position texts in this panel cannot translated directly. It is very strange. It seems that these translations come from the below settings (eg. Heading Position). Somehow the above text translations convert these setting texts translations in the way that they remove the last word ("Position").
Heading Position » Heading
Completion Date Position » Completion Date

But somehow in other language (Hungarian) it removes the last 1 character either:
Fejléc Pozíció » Fejlé
Teljesítési Dátum Pozíció » Teljesítési Dátu

**POSSIBLE SOLUTION**
Maybe it removes 9 characters, which is exactly the word "Position" plus one space character.
In Hungarian the word "Pozíció" is just 8 characters. That's why this process removes either the last character in Hungarian.

**Comment by donnapep** [comment]
To reproduce:
- Change the _Site Language_ setting in _Settings_ > _General_.
- Click the _Update translations_ button on the Dashboard > Updates page (of course, these will be called something else depending on the language selected).
- Go to _Certificates_ > _Certificate Templates_ and select a template.
