### ISSUE TITLE
Certidicate does't open in new tab or windows

### ISSUE THREAD

**Issue by davidefiorio** [woocommerce/sensei-certificates#181]
In plugin page I read:
"The certificate is a PDF document, which will open in a new browser tab, where the learner can save it or print it, as they would any other PDF document."

It doesn't work for me, Have someone an idea of what can i verify?

Tnk.
DF

**Comment by richardmtl** [comment]
Hi Davide! Please contact us here for troubleshooting this issue. This repo is meant for verified bug reports or feature requests. Thanks!

https://woocommerce.com/my-account/create-a-ticket/

**Comment by jakob-p** [comment]
Putting this in your functions.php can solve this problem

function open_certificate_in_new_tab($text) {

$return = str_replace('href="https://YOURDOMAINHERE.YXZ/certificate/', 'target="_blank" href="https://YOURDOMAINHERE.YXZ/certificate/', $text);

return $return;
}

add_filter('the_content', 'open_certificate_in_new_tab');
