### ISSUE TITLE
Certificate error when not logged in and clicking on "View certificate" email link

### ISSUE THREAD

**Issue by donnapep** [woocommerce/sensei-certificates#184]
Related #174.

## Steps to Reproduce
- In _Sensei LMS_ > _Settings_ > _Email Notifications_, ensure email notifications are enabled for both the teacher and the learner when a course is completed.
- Complete a course.
- Log out of the site.
- In either of the emails, click the "View certificate" link.
- The following error appears:
![Screen Shot 2019-08-30 at 3 10 34 PM](https://user-images.githubusercontent.com/1190420/64045858-64b98e00-cb38-11e9-9733-332980769df1.jpg)

## What Should Happen Instead?
When clicking the "View certificate" link in the email, a user who is not logged in AND who has _not_ selected the "Allow my Certificates to be publicly viewed" checkbox on their learner profile page, should be redirected to the login page. Once they successfully log in, they should be redirected back to the certificate.

**Comment by richardmtl** [comment]
Raised in 2509193-zen

**Comment by donnapep** [comment]
https://wordpress.org/support/topic/change-message-you-are-not-allowed-to-view-this-certificate/

**Comment by m1r0** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Certificate error when not logged in and clicking on "View certificate" email link](https://trello.com/c/uqfxr7Zc/1231-certificate-error-when-not-logged-in-and-clicking-on-view-certificate-email-link)
