### ISSUE TITLE
Remove query string from images before using them to generate PDF

### ISSUE THREAD

**Issue by jom** [woocommerce/sensei-certificates#187]
Some hosts (such as GoDaddy)/plugins add a cache bust query string when using `wp_get_attachment_url`. We should not trust the output from that method to end with the extension. 

Alternatively, we might be able to check-for and use WP 5.3's new `wp_get_original_image_path`.

**Comment by donnapep** [comment]
Please see https://github.com/Automattic/guardians/issues/502 for context.

**Comment by donnapep** [comment]
Noting here that this is low priority because it's unlikely to occur for most users, but also because the user who originally reported the problem went to LearnDash.

**Comment by donnapep** [comment]
@jom Do you happen to recall this one? I looked at usages of `wp_get_attachment_url` and it's called by `sensei_create_master_certificate_template`, which is only called when the example certificate template is created on plugin install or via data updates.

`wp_get_attachment_url` is also called in `certificate_template_image_meta_box`, which is used in the meta box on the _Edit Certificate Template_ page.

In either case, it's not clear to me how `wp_get_attachment_url` is the culprit for the user not being able to view the actual certificate.

**Comment by jom** [comment]
The code that was the culprit changed a bit, so it is now masked. This was the culprit:
https://github.com/woocommerce/sensei-certificates/blob/657baab46643fc730967bec5efdce14a39c9ebcf/classes/class-woothemes-sensei-certificates.php#L887-L896

However, now this was changed in #199 and switched to a call to `get_attached_file()`. I'm not sure how/if GoDaddy hooks into that, but that PR might have fixed it.

**Comment by donnapep** [comment]
Thanks for that. I'm going to close this issue for now and we'll see if we still get tickets after that fix ships.
