### ISSUE TITLE
Certificate location after site move

### ISSUE THREAD

**Issue by PDowney** [woocommerce/sensei-certificates#190]
I recently attempted to move my site to to a new directory location one level down, example /var/www/mysite to /var/www/sites/mysite. All proper WP procedure was followed for moving a site's folder down a level. Nginx vhost file was adjusted, wp-config.php points to the right places. Everything else on the site functions correctly as it did prior to the directory move. All caches have been cleared within Nginx, PHP Opcache, Redis, and Cloudflare. Just to be safe, I verified that the issue persists through Chrome incognito mode and additional browsers in-case it was a local caching issue on my end.

When attempting to view certificates, the following error is given: "Can't open file /var/www/mysite/html/wp-content/plugins/sensei-certificates/lib/tfpdf/font/unifont/DejaVuSansCondensed.ttf".

I've attempted to locate any strings within the database that point to /var/www/mysite, and have done a wp-cli search/replace on those strings to point to /var/www/sites/mysite, but the error persists. Is this location hardcoded in the database in some way when sensei-certificates installs? 

I also ran the sensei task to recreate all certificates, which also failed to correct the issue.

My temporary solution was to use a symbolic link from the old folder to the new folder, which correcte the issue. But I'm still troubled as to where in the database the certificates are set to look for the old location.

**Comment by donnapep** [comment]
Try updating the `$ttffile` variable in `wp-content/plugins/sensei-certificates/lib/tfpdf/font/unifont/dejavusanscondensed.mtx.php`.

If that doesn't fix it, please [open a Support request](https://woocommerce.com/my-account/create-a-ticket/?primary=broken&select=152116&form=ticket) as we prefer to keep GitHub issues for confirmed bugs.
