### ISSUE TITLE
Certificate display issue when using non-Latin characters

### ISSUE THREAD

**Issue by danjjohnson** [woocommerce/sensei-certificates#210]
We've had a few reports of certificate display issues after updating from 2.0 to 2.0.1, whereby the certificate text is all piled on top of itself. e.g.

![image](https://user-images.githubusercontent.com/1990037/77161727-44d0c400-6aa2-11ea-953c-f8349f401665.png)

Unable to reproduce on a test site so far, but we're looking into this PR as a probable cause:
https://github.com/woocommerce/sensei-certificates/pull/193

Current reports:
2794054-zen
2801057-zen

**Comment by jom** [comment]
I was able to reproduce by adding a non-latin character into my template values.
