### ISSUE TITLE
Custom fonts overwritten on update

### ISSUE THREAD

**Issue by cena** [woocommerce/sensei-certificates#222]
User in 2952053-zen, in an impassioned plea, requests a way for custom fonts to  be protected during updates.

> ...every time the plugin is updated, the custom fonts are erased. If there was some sort of graceful fallback, this wouldn't be as much of a problem, but instead that instantly BREAKS the certificate functionality because the code can't load the correct font file.
> ...
> Can you PLEASE write the code necessary to detect if a custom font file is in use and preserve it during an update? Or allow us to upload the custom font to our theme directory and have the plugin look there first? As it stands, this plugin breaks on every. single. update.

**Comment by jom** [comment]
They can put the fonts in their theme directory (if it is a child theme; or anywhere else that won't get updated) and then set the `FPDF_FONTPATH` constant in their `wp-config.php` to the path of the fonts.

Since there is this option in FPDF, we probably won't do anything else to support this.

**Comment by danjjohnson** [comment]
Just noting that I added this to the docs: https://senseilms.com/documentation/sensei-certificates/
