### ISSUE TITLE
From Certificates page, Analysis duplicates learner path

### ISSUE THREAD

**Issue by cena** [woocommerce/sensei-certificates#226]
### Steps to Reproduce
1. Go to '...wp-admin/edit.php?post_type=certificate'
2. Click on a learner name
3. Page goes to Analysis->learnerName->learnerName->className
<img width="708" alt="image" src="https://user-images.githubusercontent.com/19334/83635414-cd231900-a569-11ea-9016-fbd9061f536f.png">

### PHP / WordPress / Sensei WooCommerce Paid Courses / Sensei LMS version
PHP: 7.4.1
WP: 5.4.1
Woo: 4.2.0
WCPC: 2.0.1
Certificates: 2.0.4 |

**Comment by alexsanford** [comment]
I don't think this is a bug with Certificates. When I navigate directly to Sensei LMS > Analysis > [username] > [course] I see the same thing, even with the Certificates plugin deactivated.

However, it seems that the two "usernames" are actually distinct. For me, the first one is my display name (Alex Sanford), and the second is my username (admin).

Closing this, but if you still think we should make a change, feel free to post an issue in the Sensei repo.

Thanks for the report!
