### ISSUE TITLE
Apostrophe showing as then Unicode Decimal &#8217;

### ISSUE THREAD

**Issue by dericleeyy** [woocommerce/sensei-certificates#227]
### Steps to Reproduce
1. Create a course with apostrophe `'` in the title.
2. Complete the course
3. View the certificate

### What I Expected
Title displayed with apostrophe

### What Happened Instead
Apostrophe is escaped as  `&#8217;`

### PHP / WordPress / Sensei Certificates / Sensei LMS version
WP 5.4.1
Sensei 3.0.1
Certificates 2.0.4

### Context / Source
2996022-zen

**Comment by danjjohnson** [comment]
I also see the same issue with a dash `-`

Another user has reported the same issue with `™` symbol also: 3034627-zen

**Comment by Pleiades** [comment]
Correct. When I reported this issue to @dericleeyy at WooCommerce tech support I demonstrated that WordPress translates virtually all punctuation in the title field into Unicode, and that Sensei Certificates fails to render properly. 
I'm surprised that this is well into its second week without any activity.
