### ISSUE TITLE
Date Completed is showing date started instead of date completed

### ISSUE THREAD

**Issue by dericleeyy** [woocommerce/sensei-certificates#228]
### Steps to Reproduce
1. Sign up for a course
2. Wait 10 minutes
3. Complete the course
4. View the certificate details

### What I Expected
Completed date inherits the timestamp of when the course was completed

### What Happened Instead
![image](https://user-images.githubusercontent.com/4032898/84000938-3bb40c80-a998-11ea-8507-bffbd0d2a36f.png)

The timestamp shown is the course started timestamp:

![image](https://user-images.githubusercontent.com/4032898/84000970-5090a000-a998-11ea-99a8-dd263f920ff2.png)

### PHP / WordPress / Sensei Certificates / Sensei LMS version

Certificates 2.0.4
Sensei 3.1.1

### Context / Source

3028020-zen

**Comment by donnapep** [comment]
Not able to reproduce. The second screenshot in the description shows the lesson completed date, not the course completed date. Confirmed that the course completed date is used for the certificate:

![Screen Shot 2020-06-11 at 9 22 11 AM](https://user-images.githubusercontent.com/1190420/84390479-a7c78800-abc5-11ea-8105-4bbf8a354cbb.jpg)

![Screen Shot 2020-06-11 at 9 21 50 AM](https://user-images.githubusercontent.com/1190420/84390483-a8601e80-abc5-11ea-897f-32b750152473.jpg)
