### ISSUE TITLE
Add Certificate support to block-based Courses

### ISSUE THREAD

**Issue by alexsanford** [woocommerce/sensei-certificates#261]
### Is your feature request related to a problem? Please describe

For legacy courses, the "View Certificate" button is added automatically to the Course page on completion. However, for block-based Courses, this button is not added.

### Describe the solution you'd like

A way for Learners to access their Certificate from the Course page when that Course is completed.

### Describe alternatives you've considered

This could be added as a new block which handles the certificate setup (i.e. setting the Certificate Template to be used for this Course).

### Additional context

More discussion at p6rkRX-20F-p2

**Comment by gkaragia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add 'View Certificate' button block](https://trello.com/c/aBmhonNC/907-add-view-certificate-button-block)

**Comment by aaronfc** [comment]
This has been reported by gonzalo too here: p1654601478047389-slack-C03BXN7UQ5V
