### ISSUE TITLE
Decode HTML entities in student name

### ISSUE THREAD

**Issue by langy** [woocommerce/sensei-certificates#265]
### Steps to Reproduce
1. Go to Certificates > Certificates
2. Choose a certificate issued to a user with an encodable entity in their name (e.g. `Brian O'Conner`)
3. Notice that their name shows the HTML encoded version of the entity (e.g. `Brian O&#039;Conner`)

### What I Expected
See the name with decoded HTML entities.

### What Happened Instead
Saw the name with encoded HTML entities.

### PHP / WordPress / Sensei Certificates / Sensei LMS version
PHP 7.2.34 / WordPress 5.7.2 /  Sensei Certificates 2.1.0 / Sensei LMS 2.0.0

### Browser / OS version
N/A

### Screenshot / Video
![Screen Shot 2021-05-20 at 10 12 49 am](https://user-images.githubusercontent.com/713141/118900474-60f51d00-b954-11eb-9414-2086c4596d29.png)

### Context / Source
N/A

**Comment by alexsanford** [comment]
I'm not seeing this issue on my test site. Could you try using the latest versions of Sensei Certificates (2.2.0) and Sensei LMS (3.13.0) and see if you are still seeing this problem?

**Comment by donnapep** [comment]
Closing as stale.
