### ISSUE TITLE
Fatal error: Uncaught RuntimeException: FPDF Error: Undefined font: dejavu

### ISSUE THREAD

**Issue by vinvin27** [woocommerce/sensei-certificates#268]
We are facing an issue using Sensei Certificate Plugin.

When we use Message box on place it, we having this error when preview our certificate : 

Fatal error: Uncaught RuntimeException: FPDF Error: Undefined font: dejavu

If we remove message box, its ok... 

`/home/vinvin/website//wp-content/plugins/sensei-certificates/lib/tfpdf/tFPDF/PDF.php:720 Stack trace: #0 /home/vinvin/website//wp-content/plugins/sensei-certificates/lib/tfpdf/tFPDF/PDF.php(1184): tFPDF\PDF->Error('Undefined font:...') #1 /home/vinvin/website//wp-content/plugins/sensei-certificates/classes/class-woothemes-sensei-certificate-templates.php(626): tFPDF\PDF->SetFont('dejavu', '', 40) #2 /home/vinvin/website//wp-content/plugins/sensei-certificates/classes/class-woothemes-sensei-certificate-templates.php(518): WooThemes_Sensei_Certificate_Templates->textarea_field(Object(tFPDF\PDF), 'Nous attestons ...', 0, Array, Array) #3 /home/vinvin/website//wp-content/plugins/sensei-certificates/templates/single-certificate_template.php(30): WooThemes_Sensei_Certificate_Templates->generate_pdf() #4 /home/vinvin/website//wp-includes/template-loader.php(106): include('/home/magistr/d...') #5 /h in /home/vinvin/website//wp-content/plugins/sensei-certificates/lib/tfpdf/tFPDF/PDF.php on line 720`

I added in my wp-config.

`define('FPDF_FONTPATH', $_SERVER["DOCUMENT_ROOT"].'/wp-content/plugins/sensei-certificates/lib/tfpdf/font/');`

**Comment by yscik** [comment]
Hey @vinvin27! Thanks for the report. Looks like it only happens in Preview mode, it will work fine for the learners when a PDF is generated. 
Fixing the issue in the next release with the linked PR, but it should be safe to ignore until then.

**Comment by vinvin27** [comment]
Hey @yscik - Oh sweet its working perfectly :D
