### ISSUE TITLE
Create uninstall feature to clear the plugin data

### ISSUE THREAD

**Issue by renatho** [woocommerce/sensei-certificates#281]
### Is your feature request related to a problem? Please describe

When we remove the plugin, the plugin data is persisted.

### Describe the solution you'd like

Create a feature to remove the plugin data on the uninstall.

**Comment by m1r0** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Certificates: Create uninstall feature to clear the plugin data](https://trello.com/c/fRRKADl0/1234-certificates-create-uninstall-feature-to-clear-the-plugin-data)
