### ISSUE TITLE
Unable to save "None" option for Certificate Template on PHP 8

### ISSUE THREAD

**Issue by donnapep** [woocommerce/sensei-certificates#334]
Originally reported in https://github.com/Automattic/sensei/issues/6813.

When editing a course and set `None` in the Certificate Template field on a course and hit save, and then reload, the edit course page it reverts to the old value when the site runs on PHP v.8

The system works when editing a course that doesn't have a template selected,  then select one, hit save and reload.

In other words, the saving option doesn't work when removing an excisting a certificate template on a course and the site is on PHP v.8. Confirmed it works on PHP 7.4

The user reported this on the forum: https://wordpress.org/support/topic/set-none-on-certificate-template-on-course-doesnt-work-on-php-8/#post-16645080

They also share a [screencast](https://www.dropbox.com/s/pgyi38ouwptjiug/Kurser%20%E2%80%B9%20Webbkurs-HLR%20%E2%80%94%20WordPress%20%E2%80%94%20Firefox%20Developer%20Edition%202023-04-11%2016-07-07.mp4?dl=0). 

Noting the following errors reported too: 

```
PHP Warning: Attempt to read property “display_name” on bool in C:\Laragon\www\Webbkurshlr\wp-content\plugins\sensei-certificates\classes\class-woothemes-sensei-certificates.php on line 596
PHP Warning: Attempt to read property “user_login” on bool in C:\Laragon\www\Webbkurshlr\wp-content\plugins\sensei-certificates\classes\class-woothemes-sensei-certificates.php on line 596
```

Sensei LMS v. 4.13.0.1.13.0
WordPress v. 6.2

**Comment by donnapep** [comment]
https://dotcomsales.wordpress.com/2023/06/28/sensei-demo-for-built-by-sales-team/#comment-453

**Comment by merkushin** [comment]
Interesting to notice that the plugin doesn't support PHP 8 in development :)
https://github.com/woocommerce/sensei-certificates/blob/trunk/composer.json#L5
