### ISSUE TITLE
Certificate Certificate - Rerun Update not working

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/sensei-certificates#82]
Link to ticket: https://woothemes.zendesk.com/agent/tickets/370224

If the learner complete a course prior to the Sensei Certificate plugin having been installed, they will not have access to any certificates in the My Courses Dashboard on the front end.

Equally, running the data update under **Sensei > Data Updates > Create Certificates** doesn't have any effect at all.

**Comment by richardmtl** [comment]
I have another report in 409308-zd-woothemes

**Comment by jenhooks** [comment]
The customer in richardmtl's post above has followed up asking for more details in 474718-zd-woothemes

**Comment by davoraltman** [comment]
The user in 486519-zd-woothemes confirmed (and @jenhooks also mentioned in 474718-zd-woothemes) that the users who enrolled after the certificate plugin was installed, don't receive a certificate as well.

@pgk Can you take a look at this when you have time? Thanks!

**Comment by danjjohnson** [comment]
@pgk the "Create certificates" update now works, but I did see this error during the data update:

![image](https://cloud.githubusercontent.com/assets/1990037/25277661/84abc6da-2697-11e7-9dcb-cd90c4ddfc1d.png)
