### ISSUE TITLE
Unable to open font file when previewing certificate template

### ISSUE THREAD

**Issue by josephtactica** [woocommerce/sensei-certificates#96]
I encountered a fopen error when I deployed to a staging environment. The plugin was trying to load one of the .ttf files under in `src/wordpress/wp-content/plugins/sensei-certificates/lib/tfpdf/font/unifont` when I tried to preview a custom certificate template. I fixed the issue by:

In _wp-config.php_ added:
`define('FPDF_FONTPATH', $_SERVER["DOCUMENT_ROOT"].'/wp-content/plugins/sensei-certificates/lib/tfpdf/font/');`

Remove these in repo and added it in _.gitignore_:

```
src/wordpress/wp-content/plugins/sensei-certificates/lib/tfpdf/font/unifont/*.cw.dat
src/wordpress/wp-content/plugins/sensei-certificates/lib/tfpdf/font/unifont/*.mtx.php
```

**Comment by aheckler** [comment]
537866-zd-woothemes

**Comment by aheckler** [comment]
Another workaround is to just rename the existing `.mtx.php` file like so:

`example.mtx.php` --> `example.mtx.php_BACKUP`

This allows a new file to be created in it's place.

**Comment by lschuyler** [comment]
550459-zd-woothemes

**Comment by aheckler** [comment]
Possibly 558280-zd-woothemes

**Comment by Tobias-Keller** [comment]
had the same issue on changing the server...should realy be fixed

**Comment by richardmtl** [comment]
@Tobias-Keller this was fixed in https://github.com/woocommerce/sensei-certificates/pull/124 but my understanding is that for old installs (from before this patch), the issue will remain.

**Comment by Tobias-Keller** [comment]
had this problem today and the installation is from 2 Month ago

**Comment by richardmtl** [comment]
Hmm, ok, I will re-open then; maybe @pgk will have some input as to why this might have happened.

**Comment by donnapep** [comment]
To reproduce, spin up a new [Jurassic Ninja site](https://jurassic.ninja/), install Sensei LMS & Sensei Certificates, and preview the _Example Template_ certificate template. You get the following error:

![Screen Shot 2019-10-03 at 11 42 21 AM](https://user-images.githubusercontent.com/1190420/66142209-08340d80-e5d3-11e9-8690-75f6f6870aa7.jpg)

**Comment by donnapep** [comment]
I can no longer reproduce this on Jurassic Ninja. However, I was able to reproduce by modifying the `$ttffile` variable in `wp-content/plugins/sensei-certificates/lib/tfpdf/font/unifont/dejavusanscondensed.mtx.php` to an invalid directory. The workaround for now is to open the above file and update `$ttffile` to point to the correct directory.

I'll see about submitting a PR to fix this though.
