### ISSUE TITLE
Class not found when viewing course certificate

### ISSUE THREAD

**Issue by josephtactica** [woocommerce/sensei-certificates#97]
Getting this error when viewing certificates:
`Fatal error: Class 'Sensei_Utils' not found in /src/wordpress/wp-content/plugins/sensei-certificates/classes/class-woothemes-sensei-certificates.php on line 516`

Using version **1.0.13**

**Comment by pgk** [comment]
@josephtactica are you still experiencing this with the latest certificate and sensei installed?

**Comment by donnapep** [comment]
Closing as stale.
